add_newline = true

format = """
\ue711  \
$direnv\
$directory\
$git_branch \
$git_status \
$nodejs\
$fill\
$cmd_duration \
$time \
\n$character
"""

# right_format = """
# $cmd_duration
# $time
# """

# [os]
# format = "[$symbol](bold white)"
# disabled = false
# [os.symbols]
# Macos = " " #リンゴのicon
# Ubuntu = " " #Ubuntuのicon

[directory]
truncation_length = 30
truncation_symbol = ".../"
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = ' ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 50
truncation_symbol = ''
# style = 'fg:#7aa2f7 bg:#1a1b26'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
# style = 'fg:#e0af68 bg:#1a1b26'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a bg:#1a1b26'
deleted_style = 'fg:#9ece6a bg:#1a1b26'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[✗](bold red)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[aws]
disabled = true

[fill]
symbol = '─'
style = 'blue'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'
